name: ${name}
description: "Plugin used for srnyx's mc-server-templates repository"
authors:
  - srnyx
website: https://srnyx.com

main: xyz.srnyx.mcservertemplates.MCServerTemplates
version: ${version}
